---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 22933.
--- DateTime: 2026/6/23 9:00
---
-- 接收参数
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
-- 拼接Redis key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 1. 检查库存
local stock = redis.call('get', stockKey)
if tonumber(stock) <= 0 then
    return 1  -- 库存不足
end

-- 2. 检查用户是否已购买
local isMember = redis.call('sismember', orderKey, userId)
if isMember == 1 then
    return 2  -- 重复购买
end

-- 3. 扣减库存 + 记录订单
redis.call('decr', stockKey)
redis.call('sadd', orderKey, userId)
--4.发送消息到队列中 XADD stream.orders * k1 vI k2 v2
redis.call('xadd','stream.order', '*','userId',userId,'voucherId',voucherId,'id',orderId)

return 0  -- 秒杀成功