---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 22933.
--- DateTime: 2026/6/17 17:05
-- 解锁Lua脚本：先判断锁的持有者，再决定是否删除
-- KEYS[1] = 锁的key
-- ARGV[1] = 当前线程的唯一标识（锁的值）

-- 1. 获取Redis中锁的值
local lockValue = redis.call('get', KEYS[1])

-- 2. 如果锁不存在 或 持有者不是当前线程，返回0（释放失败）
if lockValue == false or lockValue ~= ARGV[1] then
    return 0
end

-- 3. 删除锁（释放成功）
redis.call('del', KEYS[1])
return 1